version: "2.29.1"

networks:
  app-network:
    driver: bridge

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 20s
      timeout: 5s
      retries: 10
    restart: no
    networks:
      - app-network
  pastebin:
    container_name: pastebin
    build: .
    ports:
      - 8081:8081
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      PASTEBIN_REDIS_HOST: redis
      PASTEBIN_REDIS_PORT: 6379
    restart: no
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redis_data:/var/lib/redis/data
    networks:
      - app-network
volumes:
  postgres_data:
  redis_data:
