spring:
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: sa
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  mail:
    host: smtp.yandex.ru
    port: 465
    username: misha.shevluagin
    password: xsqnlyehnxggquvv
    test-connection: true
    protocol: smtps